### ISSUE TITLE
close trade confusion

### ISSUE THREAD

**Issue by deathmaths11** [jamespeterschinner/async_v20#7]
Please provide the follow

Description of issue:
I am getting confused on how to close the order. we see cancel order, close position, close trades, we don't know how to tell the difference so can you please clarify it?

Your environment(os, python, packages)

Expected behaviour:

Actual behaviour:

Complete self contained example of issue:

**Comment by jamespeterschinner** [comment]
Yes, It can be a little confusing. 

I believe:
 - **cancel_order** applies to pending orders that have yet to filled by OANDA
 - **close_position** close's the aggregation of current trades
 - **close_trades** will close the specific trade of a position. 

This can be a little confusing and needs to be researched to provide the correct information.
Documentation will be updated in due course 

Thanks for the feedback!

**Comment by deathmaths11** [comment]
@jamespeterschinner awesome but it just doesn't really make sense how close trades is closing a position and how close position is closing a trade. 

you can see on the oanda trading website, there is trades and positions. l made two AUD_USD trades but only shows up as one position, meaning they are both combined. 

so l am guessing l should be using the close position more since close trades might close two of my AUD_USD trades if l only want to close one.

Edit: sorry to make your life harder mate

**Comment by jamespeterschinner** [comment]
*OandaClient*.**close_trade(** *specifier* **)** will close that trades portion of a position. 

Yes you are correct trades are aggregated into positions. 

It is actually the other way around. Using **close_position** can close all trades for the specified instrument (long or short, if specified). **close_trade** cannot. 

I hope this helps. 

I'm closing the issue as I believe this information is out side the scope of async_v20.
